### ISSUE TITLE
Creator of the original here

### ISSUE THREAD

**Issue by DaRealMonika** [64-Tesseract/Erekir-Logic-Improved#1]
idk much about github so idk if there's like a way to comment instead of reporting an issue  ut if you would may you please put a link of the original mod in the desc of this mod bc before i looked at the repo for this mod i thought it was like it's own separate mod or smth else lol.

**Comment by 64-Tesseract** [comment]
All good, I added it 👍

**Comment by DaRealMonika** [comment]
thx
